# Dependencies
highlighter:      pygments

# Setup
title:            École
tagline:          'Learning Environments'
description:      'Extensible Combinatorial Optimization Learning Environments to encourage reporducible OR research.'
url:              https://www.ecole.ai
baseurl:          /

author:
  name:           'Chair'
  url:            https://cerc-datascience.polymtl.ca/

paginate:         5

# Custom vars
version:          0.0.0

github:
  repo:           https://github.com/ds4dm/ecole
